openapi: 3.0.0
info:
  title: Call Booking API
  version: 0.0.0
tags: []
paths:
  /bookings:
    post:
      operationId: GuestBookingApi_createBooking
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
        '409':
          description: The request conflicts with the current state of the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingConflictErrorResponse'
        '422':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidSlotErrorResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingRequest'
  /event_types:
    get:
      operationId: GuestEventTypeApi_listEventTypes
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventType'
  /event_types/{event_type_id}:
    get:
      operationId: GuestEventTypeApi_getEventType
      parameters:
        - name: event_type_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventType'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
  /event_types/{event_type_id}/slots:
    get:
      operationId: GuestEventTypeApi_listAvailableSlots
      parameters:
        - name: event_type_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimeSlot'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
  /owner/bookings:
    get:
      operationId: OwnerApi_listUpcomingBookings
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
  /owner/event_types:
    get:
      operationId: OwnerApi_listEventTypes
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventType'
    post:
      operationId: OwnerApi_createEventType
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventTypeRequest'
components:
  schemas:
    Booking:
      type: object
      required:
        - id
        - event_type_id
        - event_type_name
        - guest_name
        - guest_email
        - start_at
        - end_at
      properties:
        id:
          type: integer
          format: int64
        event_type_id:
          type: integer
          format: int64
        event_type_name:
          type: string
        guest_name:
          type: string
        guest_email:
          type: string
        start_at:
          type: string
          format: date-time
        end_at:
          type: string
          format: date-time
    BookingConflictErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    CreateBookingRequest:
      type: object
      required:
        - event_type_id
        - start_at
        - guest_name
        - guest_email
      properties:
        event_type_id:
          type: integer
          format: int64
        start_at:
          type: string
          format: date-time
        guest_name:
          type: string
        guest_email:
          type: string
    CreateEventTypeRequest:
      type: object
      required:
        - name
        - description
        - duration_minutes
      properties:
        name:
          type: string
        description:
          type: string
        duration_minutes:
          type: integer
          format: int32
          minimum: 1
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    EventType:
      type: object
      required:
        - id
        - name
        - description
        - duration_minutes
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        duration_minutes:
          type: integer
          format: int32
          minimum: 1
    InvalidSlotErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    NotFoundErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    TimeSlot:
      type: object
      required:
        - start_at
        - end_at
      properties:
        start_at:
          type: string
          format: date-time
        end_at:
          type: string
          format: date-time
servers:
  - url: http://localhost:3000
    variables: {}
